// Display labels from the supplied Anexo 22 (15 January 2026), appendices 1-4, 12-14.
// English names are interface translations, not legal interpretations.
type Labels = Record<string, Record<string, readonly [string, string]>>;
export const CUSTOMS_LABELS: Labels = {
  customs: {
    "160": ["Manzanillo", "Manzanillo"],
    "240": ["Nuevo Laredo", "Nuevo Laredo"],
    "270": ["Piedras Negras", "Piedras Negras"],
    "271": ["Aeropuerto Plan de Guadalupe", "Plan de Guadalupe Airport"],
    "430": ["Veracruz", "Veracruz"],
    "470": ["Aeropuerto Ciudad de México", "Mexico City Airport"],
    "480": ["Guadalajara", "Guadalajara"],
    "520": ["Monterrey", "Monterrey"],
    "521": ["Aeropuerto Mariano Escobedo", "Mariano Escobedo Airport"],
    "651": ["San Cayetano Morelos, Toluca", "San Cayetano Morelos, Toluca"],
    "730": ["Aguascalientes", "Aguascalientes"],
    "731": ["Interpuerto San Luis Potosí", "San Luis Potosi Intermodal Port"],
    "800": ["Colombia, Nuevo León", "Colombia, Nuevo Leon"],
    "810": ["Altamira", "Altamira"],
    "840": ["Guanajuato", "Guanajuato"],
    "850": ["Aeropuerto Felipe Ángeles", "Felipe Angeles Airport"],
  },
  documents: {
    A1: ["Importación / exportación definitiva", "Permanent import / export"],
    A3: ["Regularización de mercancías", "Goods regularization"],
    AF: ["Activo fijo temporal (IMMEX)", "Temporary fixed assets (IMMEX)"],
    BO: [
      "Reparación / sustitución y retorno",
      "Repair / replacement and return",
    ],
    F4: ["Cambio de régimen de insumos", "Input customs regime change"],
    F5: ["De temporal a definitiva", "Temporary to permanent import"],
    IN: [
      "Insumos temporales (IMMEX)",
      "Temporary manufacturing inputs (IMMEX)",
    ],
    RT: ["Retorno de mercancías (IMMEX)", "Return of goods (IMMEX)"],
    V1: ["Transferencias virtuales", "Virtual goods transfers"],
    R1: ["Rectificación de pedimento", "Declaration amendment"],
  },
  headerTaxes: {
    "1": ["DTA · Trámite aduanero", "DTA · Customs processing fee"],
    "2": ["Cuotas compensatorias", "Countervailing duties"],
    "3": ["IVA · Valor agregado", "VAT · Value-added tax"],
    "4": ["ISAN · Automóviles nuevos", "ISAN · New vehicle tax"],
    "6": [
      "IGI / IGE · Importación / exportación",
      "IGI / IGE · Import / export duty",
    ],
    "7": ["Recargos", "Surcharges"],
    "9": ["Otros", "Other"],
    "11": ["Multas", "Penalties"],
    "12": ["Contribuciones T-MEC 2.5", "USMCA article 2.5 duties"],
    "13": ["Recargos T-MEC 2.5", "USMCA article 2.5 surcharges"],
    "15": ["Prevalidación", "Prevalidation fee"],
    "16": ["Contribuciones EUR", "EUR duties"],
    "17": ["Recargos EUR", "EUR surcharges"],
    "20": ["Medida de transición", "Transition measure"],
    "22": ["IEPS · Gasolina", "Excise tax · Gasoline"],
    "23": ["IVA de prevalidación", "VAT on prevalidation"],
    "50": ["Diferencia a favor", "Taxpayer credit difference"],
  },
  paymentMethods: {
    "0": ["Efectivo", "Cash payment"],
    "2": ["Fianza", "Bond"],
    "4": ["Depósito en cuenta aduanera", "Customs account deposit"],
    "5": ["Temporal no sujeta a impuestos", "Non-taxable temporary import"],
    "6": ["Pendiente de pago", "Payment pending"],
    "7": ["Partida presupuestal federal", "Federal budget allocation"],
    "8": ["Franquicia", "Allowance"],
    "9": ["Exento de pago", "Exempt"],
    "12": ["Compensación", "Offset"],
    "13": ["Pago ya efectuado", "Previously paid"],
    "15": ["Cuenta aduanera de garantía", "Customs guarantee account"],
    "16": ["Acreditamiento", "Tax credit application"],
    "18": ["Estímulo fiscal", "Tax incentive"],
    "19": ["Otros medios de garantía", "Other guarantees"],
    "21": ["Crédito en IVA e IEPS", "VAT and excise tax credit"],
    "22": ["Garantía en IVA e IEPS", "VAT and excise guarantee"],
  },
  incoterms: {
    CIF: ["Costo, seguro y flete", "Cost, insurance and freight"],
    CIP: ["Transporte y seguro pagados", "Carriage and insurance paid"],
    CPT: ["Transporte pagado", "Carriage paid to"],
    DAP: ["Entregada en lugar", "Delivered at place"],
    DDP: ["Entregada derechos pagados", "Delivered duty paid"],
    DPU: ["Entregada y descargada", "Delivered at place unloaded"],
    EXW: ["En fábrica", "Ex works"],
    FCA: ["Franco transportista", "Free carrier"],
    FOB: ["Franco a bordo", "Free on board"],
    CFR: ["Costo y flete", "Cost and freight"],
    FAS: ["Franco al costado del buque", "Free alongside ship"],
  },
};
const COUNTRIES: Record<string, string> = {
  ARG: "AR",
  AUT: "AT",
  BRA: "BR",
  CAN: "CA",
  CHE: "CH",
  CHN: "CN",
  CRI: "CR",
  CZE: "CZ",
  DEU: "DE",
  DOM: "DO",
  ESP: "ES",
  FRA: "FR",
  GBR: "GB",
  HKG: "HK",
  HUN: "HU",
  IDN: "ID",
  IND: "IN",
  ITA: "IT",
  JPN: "JP",
  MEX: "MX",
  MYS: "MY",
  NIC: "NI",
  POL: "PL",
  ROM: "RO",
  RUS: "RU",
  SGP: "SG",
  SRB: "RS",
  SUR: "SR",
  THA: "TH",
  TUR: "TR",
  TWN: "TW",
  USA: "US",
  VNM: "VN",
  ZYA: "NL",
};
export function customsLabel(
  key: string,
  dimension: string,
  language: "es" | "en",
): string | undefined {
  if (dimension === "countries" && COUNTRIES[key]) {
    return `${key} · ${new Intl.DisplayNames([language], { type: "region" }).of(COUNTRIES[key])}`;
  }
  const label = CUSTOMS_LABELS[dimension]?.[key];
  if (label) return `${key} · ${label[language === "es" ? 0 : 1]}`;
  if (CUSTOMS_LABELS[dimension] || dimension === "countries") {
    return `${key} · ${language === "es" ? "Sin descripción validada" : "Description not verified"}`;
  }
  return undefined;
}
